### ISSUE TITLE
What is `distribution` defined in `Ballerina.toml`? 

### ISSUE THREAD

**Issue by nicokosi** [jreleaser/helloworld-ballerina#1]
Hello, 👋 
Just curious, what is [`distribution` defined in `Ballerina.toml`](https://github.com/jreleaser/helloworld-ballerina/blob/ec6314c3f8c7d1309793f5a226f734dac6a14602/Ballerina.toml#L2)?
```
[package]
distribution = "2201.3.0"
name="helloworld"
org="jreleaser"
version="1.0.0-SNAPSHOT"
```

**Comment by aalmiray** [comment]
I believe this is the version of the Ballerina runtime to be used.

**Comment by nicokosi** [comment]
OK, thanks. 👍 
Indeed, Ballerina runtime has an unusual versioning scheme (I thought "2201" was a typo 😉): 
https://ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.3.1 🤯
